//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_FACTOR
    {
        public int InstrumentId { get; set; }
        public int ProfileId { get; set; }
        public double Value { get; set; }
        public System.DateTime VolDate { get; set; }
        public string Key { get; set; }
    }
}
